export const USER_DISPATCH = 'USER_DISPATCH';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_BOOK = 'GET_BOOK';
export const SET_CURRENT_BOOK = 'SET_CURRENT_BOOK';

export const GET_EXCHANGE_BOOKS = "GET_EXCHANGE_BOOKS";


export const GET_REVIEWS_BOOK = 'GET_REVIEWS_BOOK';
